send_command:
  name: Отправить команду
  description: Отправляет пользовательскую команду на Oppo UDP-20x.
  fields:
    command:
      name: Команда
      description: Команда для отправки на Oppo UDP-20x (например, right).
      required: true
      example: "right"
      selector:
        text:
