send_command:
  name: Отправить команду
  description: Отправляет пользовательскую команду на Oppo UDP-20x.
  fields:
    command:
      name: Команда
      description: "Команда для отправки на Oppo UDP-20x: up - Вверх, down - Вниз, left - Влево, right - Вправо, enter - Подтвердить, home - Главный экран"
      required: true
      example: "right"
      selector:
        select:
          options:
            - "up"
            - "down"
            - "left"
            - "right"
            - "enter"
            - "home"
          custom_value: true
