send_command:
  name: Отправить команду
  description: Отправляет пользовательскую команду на Oppo UDP-20x.
  fields:
    command:
      name: Команда
      description: >-
        Команда для отправки на Oppo UDP-20x:
        
        - up: Переместить курсор вверх
        - down: Переместить курсор вниз
        - left: Переместить курсор влево
        - right: Переместить курсор вправо
        - enter: Выбрать/Подтвердить
        - home: Вернуться на главный экран
      required: true
      example: "right"
      selector:
        text:
          multiline: false
          type: text
          suffix: ""
          prefix: ""
          autocomplete: "up|down|left|right|enter|hom"
