send_command:
  name: Отправить команду
  description: Отправляет пользовательскую команду на Oppo UDP-20x.
  fields:
    command:
      name: Команда
      description: "Команда для отправки на Oppo UDP-20x"
      required: true
      example: "right"
      selector:
        select:
          options:
            - label: "Вверх"
              value: "up"
            - label: "Вниз"
              value: "down"
            - label: "Влево"
              value: "left"
            - label: "Вправо"
              value: "right"
            - label: "Подтвердить"
              value: "enter"
            - label: "Главный экран"
              value: "home"
          mode: dropdown
          custom_value: true
send_command:
  name: Отправить команду
  description: Отправляет пользовательскую команду на Oppo UDP-20x.
  fields:
    command:
      name: Команда
      description: "Команда для отправки (up, down, left, right, enter, home)"
      required: true
      selector:
        text:
          type: text
